Repository opentelekomcloud-infra/alerta, pull requests merged in 2020-08, with the labels that each got.

#7 New topic map for better message handling
  plugins/zulip/alerta_zulip.py
  plugins/zulip/zulipbot/config/resources/db_init_data.yaml
  plugins/zulip/zulipbot/config/resources/db_structure.yaml
  plugins/zulip/zulipbot/config/static_config.py
  plugins/zulip/zulipbot/database.py
Labels: bug

#8 Fix/repeat alerts
  plugins/zulip/alerta_zulip.py
Labels: bug

#11 Fix/server timezone
  plugins/zulip/alerta_zulip.py
Labels: bug, gate

#12 Add promote job
  .zuul.yaml
Labels: gate

#13 Fix promote job
  .zuul.yaml
Labels: gate

#14 Fix/skip
  plugins/zulip/alerta_zulip.py
Labels: bug, gate
